spring:
  datasource:
    url: jdbc:mysql://${HOST}:${PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 9090
